### ISSUE TITLE
DB 관련 문의 사항

### ISSUE THREAD

**Issue by plooox** [modooSugangOrg/modooSugang_DB#1]
1. student_log 테이블에 과목 관련 정보가 없습니다. 과목 코드를 table에 추가해야할거 같습니다.
    예시) ![image](https://user-images.githubusercontent.com/82520143/163537478-d6620e31-fe87-4ab9-b436-38238197b642.png)

2. 변수명이 이상한게 몇개 보이는데, (university_univ_name 등등..) 의도적으로 저렇게 설정한 건가요?

**Comment by ktaehyun** [comment]
1. 아아 넵 그런 거 같네요 알겠습니다
2. 그거 관계 설정하면서 자동으로 만들어지는 거라서 저렇게 만들어진 것 같아요 1번 수정하면서 컬럼명만 변경하면 되니까 같이 수정해서 다시 업데이트 할게요
